<?php

namespace Tests\Feature;

use App\Http\Controllers\Admin\ModuleController;
use App\Models\Module;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class ModuleTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate --seed');

        $user = User::find(1);

        $this->actingAs($user);
    }

    /** @test*/
    public function create_module_test()
    {
        $module = factory(Module::class)->make();

        $this->post(route('admin.module.store'),$module->toArray());

        $this->assertDatabaseHas('modules',[
            'name' => $module->name,
            'short_name' => $module->short_name,
            'block' => $module->block,
        ]);
    }

    /** @test*/
    public function delete_module_test()
    {
        $module = factory(Module::class)->create();

        $this->delete(route('admin.module.destroy', $module->id));

        $this->assertDatabaseMissing('modules',[
            'id' => $module->id,
        ]);
    }

    /** @test*/
    public function edit_module_test()
    {
        $module = factory(Module::class)->create();
        $module->name = 'Random dancing';

        $this->put(route('admin.module.update', $module->id),$module->toArray());

        $this->assertDatabaseHas('modules',[
            'name' => 'Random dancing',
        ]);
    }

}
